spring:
  application:
    name: customer-support-hub

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/customer_support_hub}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:customer-support-hub-secret-key-for-home-assignment-2026}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always